### ISSUE TITLE
environment installation

### ISSUE THREAD

**Issue by MeinhardMark** [bashirulazam/within-triplet-debias#1]
I find it almost impossible to install the environment in [this repo](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch).
Can you share your installation detail?

**Comment by bashirulazam** [comment]
Hi, 

I followed the instruction exactly in that repo and my installation detail will be the same as that repo. The only difference is the GQA dataset. I will upload the full installation with GQA very soon. However, as I said, my installation follows the exact instruction from the repo by Kang et al. 

Thanks
